<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
    <?php wp_head(); ?>
</head>

<body>
    <div class="wrap">
        <div id="primary" class="content-area">
            <main id="main" class="site-main" role="main">
                <div id="cl2b">
                    This text will be replace when the SPA build (generated by Webpack) is enqueued in WordPress.
                </div><!-- #vue-app -->
            </main><!-- #main -->
        </div><!-- #primary -->
    </div><!-- .wrap -->
    <?php wp_footer(); ?>
</body>

</html>
